Refactor network classes and work around driver issue
mullvad/windows-libraries pull request #20
Opened 2019-11-29 15:53 UTC by dlon

Overall changes:
* Move `NciContext` (for network adapter naming) and `InterfaceUtils` into libcommon.
* Generalize `InterfaceUtils::NetworkAdapter`.
* Work around Windows 8 network adapter issue.

2019-11-29 21:45 UTC, mvd-ows requested changes
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/20)* status: 4 of 6 files reviewed, 12 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[src/libcommon/network/interfaceutils.h, line 3 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lusxejl3HYsqclQm29a:-Lusxejl3HYsqclQm29b:blg0laj) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/interfaceutils.h#L3)):*
> ```objc
> #pragma once
> 
> #include <libcommon/network/ncicontext.h>
> ```

This could be `#include "ncicontext.h"` to make it immediately apparent that it's a companion file.
___
*[src/libcommon/network/interfaceutils.cpp, line 13 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-LusyoEv9sAGWxE6xwvU:-LusyoEv9sAGWxE6xwvV:b-l5ylz1) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/interfaceutils.cpp#L13)):*
> ```cpp
> 	const NciContext &nci,
> 	std::shared_ptr<std::vector<uint8_t>> addressesBuffer,
> 	PIP_ADAPTER_ADDRESSES entry
> ```

Const reference? Or make the parameter an r-value type and `std::move` into `m_entry`.
___
*[src/libcommon/network/ncicontext.h, line 13 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Luszr154F26QyXffb6m:-Luszr154F26QyXffb6n:b-gizwqh) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.h#L13)):*
> ```objc
> {
> 
> class NciContext
> ```

`Context` seems a little mismatched. How about changing it to e.g `Wrapper`, `Provider`, or just removing that part of the name?
___
*[src/libcommon/network/ncicontext.h, line 15 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut1-BU90u5ArhNawpi:-Lut1-BU90u5ArhNawpj:b615nei) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.h#L15)):*
> ```objc
> class NciContext
> {
> 	HMODULE dllHandle;
> ```

Please update this to follow the naming convention for member variables.
___
*[src/libcommon/network/ncicontext.h, line 23 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut-DTi4g1JIuuu-BmD:-Lut-DTi4g1JIuuu-BmE:b-fbtbey) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.h#L23)):*
> ```objc
> 	nciSetConnectionNameFunc m_nciSetConnectionName;
> 
> 	NciContext(NciContext&) = delete;
> ```

Maybe move the operator declarations together like we always do? Doesn't matter if these are `public` since they're also deleted.
___
*[src/libcommon/network/ncicontext.h, line 32 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut-jT32M1dC0EZf5JL:-Lut-jT4APBpPY368HD7:b-acokwg) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.h#L32)):*
> ```objc
> 
> 	NciContext(NciContext&&) = default;
> 	NciContext& operator=(NciContext&&) = default;
> ```

My bad, I didn't think this through. The instance on the left hand side would be discarded and leak `dllHandle`.
___
*[src/libcommon/network/ncicontext.cpp, line 2 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut07x6ELTXEl1s1Lfc:-Lut07x6ELTXEl1s1Lfd:b-5iriv7) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L2)):*
> ```cpp
> #include "stdafx.h"
> #include "libcommon/network/ncicontext.h"
> ```

This can be just `ncicontext.h` and the includes below could use `<>`.
___
*[src/libcommon/network/ncicontext.cpp, line 13 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut0LBg0R1Wh5PE7AT9:-Lut0LBg0R1Wh5PE7ATA:b-yk10zi) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L13)):*
> ```cpp
> NciContext::NciContext()
> {
> 	std::wstring systemDir = common::fs::GetKnownFolderPath(
> ```

The last two arguments are pretty much always the same values. I'll make an overload for this at some point.

Also, `systemDir` can be const?
___
*[src/libcommon/network/ncicontext.cpp, line 18 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut0lNL4cXAfGY0RenS:-Lut0lNL4cXAfGY0RenT:b-hjpb24) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L18)):*
> ```cpp
> 		nullptr
> 	);
> 	const auto lsassPath = std::filesystem::path(systemDir).append(L"nci.dll");
> ```

Variable name.
___
*[src/libcommon/network/ncicontext.cpp, line 33 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut1Xjb4F2UB5EmQiNe:-Lut1Xjb4F2UB5EmQiNf:b87uf0g) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L33)):*
> ```cpp
> 	{
> 		FreeLibrary(dllHandle);
> 		throw std::runtime_error("Failed to obtain pointer to nciGetConnectionName");
> ```

Capital `N`? And below as well.
___
*[src/libcommon/network/ncicontext.cpp, line 60 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut29p2Bu_eIrlVWozo:-Lut29p3CFu0TCB54_Oh:b37sj7z) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L60)):*
> ```cpp
> 		common::error::Throw(
> 			"NciGetConnectionName() failed",
> 			status
> ```

Is this a Windows error code or a value from some module/function specific enum?

If it's the former you can change the check above to `ERROR_SUCCESS != status`. If it's the latter, `Throw` is likely not the correct function to use.
___
*[src/libcommon/network/ncicontext.cpp, line 67 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut31SkD7a4qMG3_s28:-Lut31SkD7a4qMG3_s29:b-8f9fjx) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L67)):*
> ```cpp
> 	buffer.resize(nameLen / sizeof(wchar_t));
> 
> 	DWORD capacity = static_cast<DWORD>(buffer.capacity() * sizeof(wchar_t));
> ```

Refer discussion about reserved/committed memory.

Even if `capacity()` returns the number of committed bytes available, this is still wrong. Because the API function could decide to write more than `size()` characters and damage the internal consistency of the string instance.

You need `size()` and probably some +1.

Alternatively, use a vector to manage the memory and instantiate a string before returning. This is what I would do. The code will be simpler and the extra allocations / buffer copy is cheap enough that we don't need to care about the associated performance loss.


<!-- Sent from Reviewable.io -->

2019-12-02 13:19 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/20)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @mvd-ows)

___
*[src/libcommon/network/ncicontext.cpp, line 33 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut1Xjb4F2UB5EmQiNe:-Lv5itkX-dSYVQa4rNtU:bt2vr1b) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L33)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Capital `N`? And below as well.
</blockquote></details>

Fixed.
___
*[src/libcommon/network/ncicontext.cpp, line 60 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut29p2Bu_eIrlVWozo:-Lv5ivcw6RdAvfkbfsdo:brr4jzd) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L60)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Is this a Windows error code or a value from some module/function specific enum?

If it's the former you can change the check above to `ERROR_SUCCESS != status`. If it's the latter, `Throw` is likely not the correct function to use.
</blockquote></details>

I'm going to check only whether it's non-zero for now, since I'm uncertain or whether it sets "last error" or whether the status code is any more specific than that.
___
*[src/libcommon/network/ncicontext.cpp, line 67 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut31SkD7a4qMG3_s28:-Lv5k0dV8pFz5UnywUWH:b-53k05k) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L67)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Refer discussion about reserved/committed memory.

Even if `capacity()` returns the number of committed bytes available, this is still wrong. Because the API function could decide to write more than `size()` characters and damage the internal consistency of the string instance.

You need `size()` and probably some +1.

Alternatively, use a vector to manage the memory and instantiate a string before returning. This is what I would do. The code will be simpler and the extra allocations / buffer copy is cheap enough that we don't need to care about the associated performance loss.
</blockquote></details>

This is no longer relevant because the code's been updated, but doesn't `capacity()` refer to the size of the internal array? Anyhow, I did find that the null character was included in the wstring itself, so there was a problem there, even though it didn't cause any problems in practice.
___
*[src/libcommon/network/ncicontext.h, line 15 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut1-BU90u5ArhNawpi:-Lv5ig02A1959HikJJ73:b-896fix) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.h#L15)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Please update this to follow the naming convention for member variables.
</blockquote></details>

Done.
___
*[src/libcommon/network/ncicontext.h, line 23 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut-DTi4g1JIuuu-BmD:-Lv5ii8QB7DFganLjL_u:b-896fix) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.h#L23)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Maybe move the operator declarations together like we always do? Doesn't matter if these are `public` since they're also deleted.
</blockquote></details>

Done.
___
*[src/libcommon/network/ncicontext.h, line 32 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut-jT32M1dC0EZf5JL:-Lv5ijEH240JvooAWHQ4:bp3aow6) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.h#L32)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

My bad, I didn't think this through. The instance on the left hand side would be discarded and leak `dllHandle`.
</blockquote></details>

Reverted.


<!-- Sent from Reviewable.io -->

2019-12-02 13:34 UTC, mvd-ows reviewed
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/20)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @mvd-ows)



<!-- Sent from Reviewable.io -->

2019-12-02 13:59 UTC, mvd-ows requested changes
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/20)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[src/libcommon/network/nci.cpp, line 53 at r2](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lv5u9bv8lw5-9WQnsch:-Lv5u9bv8lw5-9WQnsci:b-va1fyr) ([raw file](https://github.com/mullvad/windows-libraries/blob/3ae0952c985bf406124ab001cc9a90b058ab333e/src/libcommon/network/nci.cpp#L53)):*
> ```cpp
> 	if (0 != m_nciGetConnectionName(&guid, nullptr, 0, &nameLen))
> 	{
> 		throw std::runtime_error("NciGetConnectionName() failed");
> ```

This seems appropriate. I verified that these functions do not call `SetLastError`.
___
*[src/libcommon/network/nci.cpp, line 57 at r2](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lv5pJ7d9fclVGjuu24X:-Lv5pJ7d9fclVGjuu24Y:bcv6pzf) ([raw file](https://github.com/mullvad/windows-libraries/blob/3ae0952c985bf406124ab001cc9a90b058ab333e/src/libcommon/network/nci.cpp#L57)):*
> ```cpp
> 
> 	std::wstring buffer;
> 	buffer.reserve(nameLen / sizeof(wchar_t));
> ```

This is not compliant code? The API will be writing the zero terminator past the end of the accessible buffer.

I'm sure it works and will continue to work (given that `reserve()` commits the memory up front) but it should be possible to find a better way.
___
*[src/libcommon/network/ncicontext.cpp, line 67 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut31SkD7a4qMG3_s28:-Lv5qD13EAhjmhk5obpg:bgz66ih) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L67)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is no longer relevant because the code's been updated, but doesn't `capacity()` refer to the size of the internal array? Anyhow, I did find that the null character was included in the wstring itself, so there was a problem there, even though it didn't cause any problems in practice.
</blockquote></details>

It does cause practical issues. What if you call `size()` when writing the string to a log file? Embedded zero in the middle of the log file.

We need data integrity at all points, as far as possible.
___
*[src/libcommon/network/nci.h, line 28 at r2](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lv5oqO16vIQN8VWAX04:-Lv5oqO16vIQN8VWAX05:b-rzc73d) ([raw file](https://github.com/mullvad/windows-libraries/blob/3ae0952c985bf406124ab001cc9a90b058ab333e/src/libcommon/network/nci.h#L28)):*
> ```objc
> 	~Nci();
> 
> 	Nci(Nci&&) = delete;
> ```

An instance could be move-constructed or move-assigned but not copy-anything, right?


<!-- Sent from Reviewable.io -->

2019-12-02 14:14 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/20)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @mvd-ows)

___
*[src/libcommon/network/nci.cpp, line 57 at r2](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lv5pJ7d9fclVGjuu24X:-Lv5xL3u-ZIkb5v5GN2n:br24q4i) ([raw file](https://github.com/mullvad/windows-libraries/blob/3ae0952c985bf406124ab001cc9a90b058ab333e/src/libcommon/network/nci.cpp#L57)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This is not compliant code? The API will be writing the zero terminator past the end of the accessible buffer.

I'm sure it works and will continue to work (given that `reserve()` commits the memory up front) but it should be possible to find a better way.
</blockquote></details>

I don't see how? `nameLen` includes the null character.

Switched to using a vector as you suggested. I did the same in the PR on the main branch.
___
*[src/libcommon/network/ncicontext.cpp, line 67 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lut31SkD7a4qMG3_s28:-Lv5x4TX4SzcXrsS2n3c:brychfd) ([raw file](https://github.com/mullvad/windows-libraries/blob/3b8a90bf434aa4c1504dab8aa0dc239d09ae7804/src/libcommon/network/ncicontext.cpp#L67)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

It does cause practical issues. What if you call `size()` when writing the string to a log file? Embedded zero in the middle of the log file.

We need data integrity at all points, as far as possible.
</blockquote></details>

Switched to using a vector as you suggested. I did the same in the PR on the main branch.
___
*[src/libcommon/network/nci.h, line 28 at r2](https://reviewable.io/reviews/mullvad/windows-libraries/20#-Lv5oqO16vIQN8VWAX04:-Lv5xUPg2NB-R_sRkjkY:bpsbkjo) ([raw file](https://github.com/mullvad/windows-libraries/blob/3ae0952c985bf406124ab001cc9a90b058ab333e/src/libcommon/network/nci.h#L28)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

An instance could be move-constructed or move-assigned but not copy-anything, right?
</blockquote></details>

I didn't find it worthwhile to implement move since we don't need it yet, but done.


<!-- Sent from Reviewable.io -->

2019-12-02 14:27 UTC, mvd-ows reviewed
> Reviewed 1 of 7 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/20)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @mvd-ows)



<!-- Sent from Reviewable.io -->

2019-12-02 14:28 UTC, mvd-ows reviewed
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/20)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @mvd-ows)



<!-- Sent from Reviewable.io -->

2019-12-02 14:32 UTC, mvd-ows approved these changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/20)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-12-02 14:34 UTC, merged